import { AlertTriangle, Package, Warehouse, Truck, RefreshCw } from "lucide-react"
import type { ServiceLandingData } from "@/components/seo/ServiceLanding"

export const seoPages: Record<string, ServiceLandingData> = {
  "3pl-ecommerce-fulfillment": {
    slug: "3pl-ecommerce-fulfillment",
    keyword: "3pl ecommerce fulfillment",
    metaTitle: "3PL Ecommerce Fulfillment | Fast DTC Order Shipping",
    metaDescription: "3PL ecommerce fulfillment — integrated with your store, fast pick/pack, and nationwide shipping for DTC brands. Get a quote.",
    keywords: ["3pl ecommerce fulfillment", "3pl fulfillment (hub)", "3pl wms", "fulfillment center"],
    eyebrowIcon: Warehouse,
    eyebrow: "3PL & Warehousing",
    h1lead: "3PL Ecommerce",
    h1gold: "Fulfillment",
    heroSub: "DTC fulfillment wired to your store — orders sync, ship fast, and stay tracked coast to coast.",
    ctaLabel: "Get a 3PL quote",
    overviewLabel: "What we cover",
    intro: "Ecommerce fulfillment lives or dies on speed and integration. Delivery Group connects to your storefront, pulls orders automatically, and picks, packs, and ships them fast — with the inventory sync and tracking your customers expect. [[VERIFY: platforms supported / delivery speed]]",
    sections: [],
    whyLabel: "Why Delivery Group",
    whyHeading: "A full 3PL — warehousing, fulfillment, and real-time visibility.",
    whyBullets: ["Direct store integration", "Fast pick/pack & shipping", "Real-time inventory sync", "Nationwide reach + tracking"],
    relatedLabel: "Related services",
    related: [{ label: "3PL fulfillment (hub)", href: "/3pl-fulfillment" }, { label: "3PL WMS", href: "/3pl-wms" }, { label: "Fulfillment center", href: "/fulfillment-center" }, { label: "Pick and pack services", href: "/pick-and-pack-services" }],
    faqs: [],
    ctaHeading: "Ready to get started?",
    ctaSub: "Share your requirements for 3pl ecommerce fulfillment and we’ll send a tailored quote.",
    ctaBadge: "All 50 states",
  },
  "3pl-warehouse": {
    slug: "3pl-warehouse",
    keyword: "3pl warehouse",
    metaTitle: "3PL Warehouse | Third-Party Warehousing & Fulfillment",
    metaDescription: "A 3PL warehouse that stores your inventory and ships your orders — real-time stock, nationwide reach, transparent pricing. Get a quote.",
    keywords: ["3pl warehouse", "3pl fulfillment (hub)", "3pl warehousing", "3pl wms"],
    eyebrowIcon: Warehouse,
    eyebrow: "3PL & Warehousing",
    h1lead: "3PL",
    h1gold: "Warehouse",
    heroSub: "Third-party warehousing that ships — storage, fulfillment, and distribution from one partner.",
    ctaLabel: "Get a 3PL quote",
    overviewLabel: "What we cover",
    intro: "A 3PL warehouse gives you professional storage and order fulfillment without owning a building or hiring a warehouse team. Delivery Group stores your inventory and ships your orders with real-time visibility and nationwide reach. [[VERIFY: warehouse locations / sq ft]]",
    sections: [],
    whyLabel: "Why Delivery Group",
    whyHeading: "A full 3PL — warehousing, fulfillment, and real-time visibility.",
    whyBullets: ["Third-party storage + fulfillment", "Real-time inventory", "Nationwide distribution", "Transparent, scalable pricing"],
    relatedLabel: "Related services",
    related: [{ label: "3PL fulfillment (hub)", href: "/3pl-fulfillment" }, { label: "3PL warehousing", href: "/3pl-warehousing" }, { label: "3PL WMS", href: "/3pl-wms" }, { label: "Fulfillment warehouse", href: "/fulfillment-warehouse" }],
    faqs: [{ q: "Is a 3PL warehouse just storage?", a: "No — it's storage plus fulfillment: we receive, store, and ship your orders from the same warehouse." }],
    ctaHeading: "Ready to get started?",
    ctaSub: "Share your requirements for 3pl warehouse and we’ll send a tailored quote.",
    ctaBadge: "All 50 states",
  },
  "3pl-warehousing": {
    slug: "3pl-warehousing",
    keyword: "3pl warehousing",
    metaTitle: "3PL Warehousing Services | Inventory Storage & Distribution",
    metaDescription: "3PL warehousing services — professional inventory storage, management, and distribution with real-time visibility. Get a quote.",
    keywords: ["3pl warehousing", "3pl fulfillment (hub)", "3pl warehouse", "3pl wms"],
    eyebrowIcon: Warehouse,
    eyebrow: "3PL & Warehousing",
    h1lead: "3PL Warehousing",
    h1gold: "Services",
    heroSub: "Professional inventory storage, management, and distribution — outsourced to one accountable partner.",
    ctaLabel: "Get a 3PL quote",
    overviewLabel: "What we cover",
    intro: "3PL warehousing covers the storage and inventory-management side of logistics: receiving, putaway, cycle counts, and distribution. Delivery Group provides warehousing with real-time inventory control, wired directly into pick/pack and shipping. [[VERIFY: capacity / locations]]",
    sections: [{ h2: "Inventory managed, not just stored", body: "Cycle counts and real-time stock levels mean you always know what's on hand and where — not a black-box warehouse." }, { h2: "Straight into fulfillment", body: "Warehousing connects directly to order fulfillment, so stored goods ship without a second vendor or hand-off." }],
    whyLabel: "Why Delivery Group",
    whyHeading: "A full 3PL — warehousing, fulfillment, and real-time visibility.",
    whyBullets: ["Receiving, putaway & cycle counts", "Real-time inventory control", "Distribution to customers & retail", "Scales with your catalog"],
    relatedLabel: "Related services",
    related: [{ label: "3PL fulfillment (hub)", href: "/3pl-fulfillment" }, { label: "3PL warehouse", href: "/3pl-warehouse" }, { label: "3PL WMS", href: "/3pl-wms" }, { label: "Fulfillment warehouse", href: "/fulfillment-warehouse" }],
    faqs: [{ q: "What's the difference between 3PL warehousing and fulfillment?", a: "Warehousing is the storage + inventory-management layer; fulfillment is picking, packing, and shipping orders. We do both." }],
    ctaHeading: "Ready to get started?",
    ctaSub: "Share your requirements for 3pl warehousing and we’ll send a tailored quote.",
    ctaBadge: "All 50 states",
  },
  "3pl-wms": {
    slug: "3pl-wms",
    keyword: "3pl wms",
    metaTitle: "3PL WMS | Warehouse Management & Inventory Visibility",
    metaDescription: "3PL with a real WMS — live inventory, order status, and reporting so you always know what's in stock and shipping. Get a quote.",
    keywords: ["3pl wms", "3pl fulfillment (hub)", "3pl warehouse", "3pl ecommerce fulfillment"],
    eyebrowIcon: Warehouse,
    eyebrow: "3PL & Warehousing",
    h1lead: "3PL WMS",
    h1gold: "Warehouse Management You Can See",
    heroSub: "A warehouse management system behind your fulfillment — live inventory, order status, and reporting.",
    ctaLabel: "Get a 3PL quote",
    overviewLabel: "What we cover",
    intro: "The WMS is what separates a real 3PL from a storage unit: live stock levels, order tracking, and reporting you can act on. Delivery Group runs fulfillment on a modern WMS, so you get accurate inventory and full order visibility without buying and running the software yourself. [[VERIFY: WMS platform name]]",
    sections: [],
    whyLabel: "Why Delivery Group",
    whyHeading: "A full 3PL — warehousing, fulfillment, and real-time visibility.",
    whyBullets: ["Live inventory & stock levels", "Order status end to end", "Reporting & analytics", "No software for you to run"],
    relatedLabel: "Related services",
    related: [{ label: "3PL fulfillment (hub)", href: "/3pl-fulfillment" }, { label: "3PL warehouse", href: "/3pl-warehouse" }, { label: "3PL ecommerce fulfillment", href: "/3pl-ecommerce-fulfillment" }, { label: "Fulfillment center", href: "/fulfillment-center" }],
    faqs: [{ q: "Do I have to buy or run the WMS?", a: "No — it's part of our service; you get the visibility without licensing or operating any software." }],
    ctaHeading: "Ready to get started?",
    ctaSub: "Share your requirements for 3pl wms and we’ll send a tailored quote.",
    ctaBadge: "All 50 states",
  },
  "courier-services": {
    slug: "courier-services",
    keyword: "courier service",
    metaTitle: "Courier Services for Business | Same-Day, White Glove & More",
    metaDescription: "Business courier services — same-day, white glove, on-demand and rush delivery with tracking and proof of delivery. Get a quote.",
    keywords: ["courier service", "same day courier", "white glove delivery", "cross docking"],
    eyebrowIcon: Truck,
    eyebrow: "Courier & Delivery",
    h1lead: "Courier Services for",
    h1gold: "Business",
    heroSub: "One courier partner for every urgency — same-day, white glove, on-demand, and rush, all tracked to the door.",
    ctaLabel: "Get a courier quote",
    overviewLabel: "What we cover",
    intro: "Business courier needs range from an urgent same-day run to a white-glove install to a scheduled on-demand route. Delivery Group covers the full range with tracking and proof of delivery on every job, so you have one accountable partner instead of a different app for each errand. [[VERIFY: coverage areas / fleet]]",
    sections: [{ h2: "Every delivery urgency, one partner", body: "From a document across town to a fragile install across the region, we match the right service level to each job — and you see it all in one place." }, { h2: "For businesses that ship often", body: "Set up an account for recurring courier runs with consolidated billing and predictable service levels." }],
    whyLabel: "Why Delivery Group",
    whyHeading: "One partner for every delivery urgency.",
    whyBullets: ["Same-day, rush & on-demand", "White glove for high-value items", "Live tracking + proof of delivery", "Business accounts & recurring routes"],
    relatedLabel: "Related services",
    related: [{ label: "Same day courier", href: "/same-day-courier" }, { label: "White glove delivery", href: "/white-glove-delivery" }, { label: "Cross docking", href: "/cross-docking" }, { label: "On-demand delivery", href: "/on-demand-delivery" }, { label: "Rush delivery", href: "/rush-delivery" }, { label: "Last-mile delivery", href: "/services/last-mile-delivery" }],
    faqs: [{ q: "What kinds of courier service do you offer?", a: "Same-day, rush, on-demand, and white glove — see the linked pages for each." }],
    ctaHeading: "Ready to get started?",
    ctaSub: "Share your requirements for courier service and we’ll send a tailored quote.",
    ctaBadge: "All 50 states",
  },
  "cross-docking": {
    slug: "cross-docking",
    keyword: "cross docking",
    metaTitle: "Cross Docking Services | Faster Throughput, Less Storage",
    metaDescription: "Cross docking services that move freight from inbound to outbound fast — less storage, faster delivery, lower cost. Get a quote.",
    keywords: ["cross docking", "courier services (hub)", "expedited shipping", "same day courier"],
    eyebrowIcon: Truck,
    eyebrow: "Courier & Delivery",
    h1lead: "Cross Docking",
    h1gold: "Services",
    heroSub: "Move freight straight from inbound to outbound — skip storage, cut handling, ship faster.",
    ctaLabel: "Get a cross docking quote",
    overviewLabel: "What we cover",
    intro: "Cross docking unloads inbound freight and reloads it directly onto outbound trucks with little or no storage in between — cutting handling, dwell time, and cost. Delivery Group runs cross-dock operations to speed distribution for high-turn and time-sensitive freight. [[VERIFY: dock capacity / locations]]",
    sections: [{ h2: "When cross docking wins", body: "Perishables, pre-sold inventory, retail replenishment, and consolidations — anything where storing product is waste, not value." }],
    whyLabel: "Why Delivery Group",
    whyHeading: "One partner for every delivery urgency.",
    whyBullets: ["Inbound-to-outbound with minimal storage", "Lower handling & storage cost", "Faster time to destination", "Ideal for high-turn freight"],
    relatedLabel: "Related services",
    related: [{ label: "Courier services (hub)", href: "/courier-services" }, { label: "Expedited shipping", href: "/services/expedited-shipping" }, { label: "Same day courier", href: "/same-day-courier" }, { label: "3PL warehouse", href: "/3pl-warehouse" }],
    faqs: [{ q: "How is cross docking different from warehousing?", a: "Warehousing stores inventory over time; cross docking moves it straight through with little or no storage." }],
    ctaHeading: "Ready to get started?",
    ctaSub: "Share your requirements for cross docking and we’ll send a tailored quote.",
    ctaBadge: "All 50 states",
  },
  "crowdfunding-fulfillment": {
    slug: "crowdfunding-fulfillment",
    keyword: "crowdfunding fulfillment",
    metaTitle: "Crowdfunding Fulfillment | Kickstarter & Indiegogo Delivery",
    metaDescription: "Crowdfunding fulfillment for Kickstarter & Indiegogo — surveys, kitting, and mass backer shipping done right. Get a quote.",
    keywords: ["crowdfunding fulfillment", "fulfillment center (hub)", "kitting services", "pick and pack services"],
    eyebrowIcon: Package,
    eyebrow: "Fulfillment",
    h1lead: "Crowdfunding",
    h1gold: "Fulfillment",
    heroSub: "Deliver on your Kickstarter or Indiegogo promise — backer kitting and mass shipping handled end to end.",
    ctaLabel: "Get a fulfillment quote",
    overviewLabel: "What we cover",
    intro: "The hardest part of a successful campaign is shipping thousands of rewards at once — different tiers, add-ons, and worldwide addresses. Delivery Group handles crowdfunding fulfillment: receive your production run, kit each reward tier, and ship to every backer accurately. [[VERIFY: campaigns handled / backer volume]]",
    sections: [{ h2: "From production run to backers", body: "We receive your manufactured units, assemble each pledge tier with its add-ons, and ship the whole campaign — so you deliver on time instead of drowning in boxes." }, { h2: "Then keep selling", body: "After the campaign, roll straight into ongoing e-commerce fulfillment on the same account — no re-platforming." }],
    whyLabel: "Why Delivery Group",
    whyHeading: "Fulfillment that scales from startup to enterprise volume.",
    whyBullets: ["Reward-tier kitting & add-ons", "Mass backer shipping", "Receiving your production run", "Tracking + backer address handling"],
    relatedLabel: "Related services",
    related: [{ label: "Fulfillment center (hub)", href: "/fulfillment-center" }, { label: "Kitting services", href: "/kitting-services" }, { label: "Pick and pack services", href: "/pick-and-pack-services" }, { label: "Small business fulfillment", href: "/small-business-fulfillment" }],
    faqs: [{ q: "Can you handle different reward tiers and add-ons?", a: "Yes — each tier is kitted with its correct items and add-ons before shipping." }],
    ctaHeading: "Ready to get started?",
    ctaSub: "Share your requirements for crowdfunding fulfillment and we’ll send a tailored quote.",
    ctaBadge: "All 50 states",
  },
  "dangerous-goods-warehouse": {
    slug: "dangerous-goods-warehouse",
    keyword: "dangerous goods warehouse",
    metaTitle: "Dangerous Goods Warehouse | Compliant DG Storage & Fulfillment",
    metaDescription: "A dangerous goods warehouse with permitted, segregated storage and compliant fulfillment for regulated products. Get a quote.",
    keywords: ["dangerous goods warehouse", "hazmat logistics (hub)", "hazmat warehouse", "hazmat storage"],
    eyebrowIcon: AlertTriangle,
    eyebrow: "Dangerous Goods",
    h1lead: "Dangerous Goods",
    h1gold: "Warehouse",
    heroSub: "Permitted, segregated warehousing for dangerous goods — stored compliantly and shipped without a second vendor.",
    ctaLabel: "Get a dangerous goods warehouse quote",
    overviewLabel: "What we cover",
    intro: "A dangerous goods warehouse has to keep regulated inventory within the rules: permitted areas, hazard-class segregation, trained staff, and documentation. Delivery Group stores and fulfills dangerous goods from one compliant operation, covering the whole chain from receiving to delivery. [[VERIFY: locations / capacity]]",
    sections: [],
    whyLabel: "Why Delivery Group",
    whyHeading: "A near-zero-competition category most 3PLs won’t touch.",
    whyBullets: ["Permitted DG warehousing", "Hazard-class segregation", "Trained handlers", "Store + fulfill in one place"],
    relatedLabel: "Related services",
    related: [{ label: "Hazmat logistics (hub)", href: "/hazmat-logistics" }, { label: "Hazmat warehouse", href: "/hazmat-warehouse" }, { label: "Hazmat storage", href: "/hazmat-storage" }, { label: "Hazmat fulfillment", href: "/hazmat-fulfillment" }],
    faqs: [{ q: "What's the difference between this and hazmat storage?", a: "Same compliant facility — 'dangerous goods warehouse' is the term for the full store-and-fulfill operation; see also our hazmat storage page." }],
    ctaHeading: "Ready to get started?",
    ctaSub: "Share your requirements for dangerous goods warehouse and we’ll send a tailored quote.",
    ctaBadge: "All 50 states",
  },
  "ecommerce-returns-management": {
    slug: "ecommerce-returns-management",
    keyword: "ecommerce returns management",
    metaTitle: "Ecommerce Returns Management | DTC Returns Solution",
    metaDescription: "An ecommerce returns solution that speeds refunds and restocks — intake, inspection, and restock wired to your store. Get a quote.",
    keywords: ["ecommerce returns management", "returns management (hub)", "reverse logistics services", "returns processing"],
    eyebrowIcon: RefreshCw,
    eyebrow: "Reverse Logistics",
    h1lead: "Ecommerce Returns",
    h1gold: "Management",
    heroSub: "A returns solution built for DTC — faster refunds for customers, faster restock for you.",
    ctaLabel: "Get an ecommerce returns quote",
    overviewLabel: "What we cover",
    intro: "For DTC brands, returns shape both customer loyalty and margin. Delivery Group provides an ecommerce returns solution that receives, inspects, and restocks returns quickly and syncs status back to your store — so customers get refunds faster and your best-sellers get back in stock sooner. [[VERIFY: refund/restock timing]]",
    sections: [],
    whyLabel: "Why Delivery Group",
    whyHeading: "Turn returns from a cost center into recovered value.",
    whyBullets: ["Fast intake, inspection & restock", "Store-synced return status", "Custom disposition rules", "Return-reason reporting"],
    relatedLabel: "Related services",
    related: [{ label: "Returns management (hub)", href: "/returns-management" }, { label: "Reverse logistics services", href: "/reverse-logistics-services" }, { label: "Returns processing", href: "/returns-processing" }, { label: "3PL ecommerce fulfillment", href: "/3pl-ecommerce-fulfillment" }],
    faqs: [],
    ctaHeading: "Ready to get started?",
    ctaSub: "Share your requirements for ecommerce returns management and we’ll send a tailored quote.",
    ctaBadge: "All 50 states",
  },
  "etsy-fulfillment": {
    slug: "etsy-fulfillment",
    keyword: "etsy fulfillment",
    metaTitle: "Etsy Fulfillment | Outsource Shipping for Your Etsy Shop",
    metaDescription: "Etsy fulfillment for growing shops — we store, pick, pack, and ship your orders so you can focus on making. Get a quote.",
    keywords: ["etsy fulfillment", "fulfillment center (hub)", "small business fulfillment", "pick and pack services"],
    eyebrowIcon: Package,
    eyebrow: "Fulfillment",
    h1lead: "Etsy Fulfillment",
    h1gold: "Services",
    heroSub: "Stop packing orders at the kitchen table — we store, pick, pack, and ship your Etsy orders for you.",
    ctaLabel: "Get a fulfillment quote",
    overviewLabel: "What we cover",
    intro: "Etsy sellers hit a wall when order volume outgrows packing by hand. Delivery Group takes over fulfillment for your Etsy shop — storing inventory and shipping orders with your branding — so you get your time back and your buyers get faster delivery. [[VERIFY: Etsy integration details]]",
    sections: [{ h2: "Keep the handmade feel", body: "We pack with your materials and inserts so the unboxing stays on-brand — the buyer never sees a change, only faster shipping." }, { h2: "Grow past the kitchen table", body: "As orders climb, capacity is there — no late nights, no missed dispatch times." }],
    whyLabel: "Why Delivery Group",
    whyHeading: "Fulfillment that scales from startup to enterprise volume.",
    whyBullets: ["Store, pick, pack & ship for you", "Branded packaging kept intact", "Real-time inventory & tracking", "Scales past hand-packing"],
    relatedLabel: "Related services",
    related: [{ label: "Fulfillment center (hub)", href: "/fulfillment-center" }, { label: "Small business fulfillment", href: "/small-business-fulfillment" }, { label: "Pick and pack services", href: "/pick-and-pack-services" }, { label: "Kitting services", href: "/kitting-services" }],
    faqs: [{ q: "Will my Etsy branding stay the same?", a: "Yes — we pack with your packaging and inserts so the customer experience is unchanged." }],
    ctaHeading: "Ready to get started?",
    ctaSub: "Share your requirements for etsy fulfillment and we’ll send a tailored quote.",
    ctaBadge: "All 50 states",
  },
  "fulfillment-center": {
    slug: "fulfillment-center",
    keyword: "fulfillment center",
    metaTitle: "Fulfillment Center | Order Fulfillment Services Nationwide",
    metaDescription: "A nationwide fulfillment center — receiving, storage, pick & pack, and fast shipping with real-time inventory. Get a fulfillment quote.",
    keywords: ["fulfillment center", "pick and pack services", "fulfillment warehouse", "kitting services"],
    eyebrowIcon: Package,
    eyebrow: "Fulfillment",
    h1lead: "Order Fulfillment",
    h1gold: "Center",
    heroSub: "Receiving, storage, pick & pack, and nationwide shipping — one fulfillment partner that scales with you.",
    ctaLabel: "Get a fulfillment quote",
    overviewLabel: "What we cover",
    intro: "A fulfillment center takes inventory off your hands and gets orders to customers fast and accurately. Delivery Group receives, stores, picks, packs, and ships your orders from facilities positioned to reach the whole country quickly — with real-time inventory and order visibility the whole way. [[VERIFY: # of facilities / avg delivery time / on-time %]]",
    sections: [],
    whyLabel: "Why Delivery Group",
    whyHeading: "Fulfillment that scales from startup to enterprise volume.",
    whyBullets: ["Receiving, storage, pick/pack, ship", "Real-time inventory & order tracking"],
    relatedLabel: "Related services",
    related: [{ label: "Pick and pack services", href: "/pick-and-pack-services" }, { label: "Fulfillment warehouse", href: "/fulfillment-warehouse" }, { label: "Kitting services", href: "/kitting-services" }, { label: "Small business fulfillment", href: "/small-business-fulfillment" }, { label: "3PL fulfillment", href: "/3pl-fulfillment" }],
    faqs: [{ q: "What does a fulfillment center cost?", a: "Pricing is per order plus storage; share SKU count and monthly volume for an exact quote." }],
    ctaHeading: "Ready to get started?",
    ctaSub: "Share your requirements for fulfillment center and we’ll send a tailored quote.",
    ctaBadge: "All 50 states",
  },
  "fulfillment-warehouse": {
    slug: "fulfillment-warehouse",
    keyword: "fulfillment warehouse",
    metaTitle: "Fulfillment Warehouse | Storage + Order Fulfillment",
    metaDescription: "A fulfillment warehouse that stores your inventory and ships your orders — real-time stock, fast pick/pack, nationwide reach. Get a quote.",
    keywords: ["fulfillment warehouse", "fulfillment center (hub)", "pick and pack services", "kitting services"],
    eyebrowIcon: Package,
    eyebrow: "Fulfillment",
    h1lead: "Fulfillment",
    h1gold: "Warehouse",
    heroSub: "Store inventory and ship orders from one warehouse — with real-time stock visibility and fast pick/pack.",
    ctaLabel: "Get a fulfillment quote",
    overviewLabel: "What we cover",
    intro: "A fulfillment warehouse combines storage and order fulfillment under one roof: your inventory is received, stored, and shipped as orders come in, without juggling a separate storage provider and 3PL. Delivery Group runs fulfillment warehousing positioned to reach the country fast. [[VERIFY: warehouse locations / sq ft]]",
    sections: [{ h2: "More than storage", body: "Inbound receiving, putaway, order picking, packing, and shipping all run from the same facility — one partner, one system of record." }],
    whyLabel: "Why Delivery Group",
    whyHeading: "Fulfillment that scales from startup to enterprise volume.",
    whyBullets: ["Storage + fulfillment in one place", "Real-time inventory visibility", "Fast, accurate pick/pack", "Nationwide shipping reach"],
    relatedLabel: "Related services",
    related: [{ label: "Fulfillment center (hub)", href: "/fulfillment-center" }, { label: "Pick and pack services", href: "/pick-and-pack-services" }, { label: "Kitting services", href: "/kitting-services" }, { label: "3PL warehouse", href: "/3pl-warehouse" }],
    faqs: [{ q: "Is this just storage or full fulfillment?", a: "Full fulfillment — we store your inventory and pick, pack, and ship orders from the same warehouse." }],
    ctaHeading: "Ready to get started?",
    ctaSub: "Share your requirements for fulfillment warehouse and we’ll send a tailored quote.",
    ctaBadge: "All 50 states",
  },
  "hazmat-3pl": {
    slug: "hazmat-3pl",
    keyword: "hazmat 3pl",
    metaTitle: "Hazmat 3PL | Compliant Fulfillment for Dangerous Goods",
    metaDescription: "A hazmat 3PL that stores, picks, packs, and ships regulated products compliantly across all 50 states. Get a hazmat 3PL quote.",
    keywords: ["hazmat 3pl", "hazmat logistics (hub)", "hazmat fulfillment", "hazmat warehouse"],
    eyebrowIcon: AlertTriangle,
    eyebrow: "Dangerous Goods",
    h1lead: "Hazmat 3PL",
    h1gold: "Fulfillment for Regulated Products",
    heroSub: "The full third-party logistics stack for hazardous goods: storage, kitting, pick/pack, and compliant delivery.",
    ctaLabel: "Get a hazmat 3PL quote",
    overviewLabel: "What we cover",
    intro: "Most 3PLs won't touch hazmat. Delivery Group runs the entire fulfillment chain for regulated products — permitted storage, compliant pick/pack, and licensed hazmat delivery — so brands selling dangerous goods get the same turnkey 3PL everyone else has. [[VERIFY: order volume / SLA]]",
    sections: [{ h2: "Why a hazmat-specialist 3PL", body: "General 3PLs decline regulated SKUs or bolt on surcharges. We're built for it: trained staff, permitted space, and licensed carriers — near-zero competition in this niche." }],
    whyLabel: "Why Delivery Group",
    whyHeading: "A near-zero-competition category most 3PLs won’t touch.",
    whyBullets: ["End-to-end hazmat fulfillment", "Permitted storage + compliant shipping", "Nationwide, all 50 states", "One vendor, full compliance"],
    relatedLabel: "Related services",
    related: [{ label: "Hazmat logistics (hub)", href: "/hazmat-logistics" }, { label: "Hazmat fulfillment", href: "/hazmat-fulfillment" }, { label: "Hazmat warehouse", href: "/hazmat-warehouse" }, { label: "3PL fulfillment", href: "/3pl-fulfillment" }],
    faqs: [],
    ctaHeading: "Ready to get started?",
    ctaSub: "Share your requirements for hazmat 3pl and we’ll send a tailored quote.",
    ctaBadge: "All 50 states",
  },
  "hazmat-fulfillment": {
    slug: "hazmat-fulfillment",
    keyword: "hazmat fulfillment",
    metaTitle: "Hazmat Fulfillment | Pick, Pack & Ship Dangerous Goods",
    metaDescription: "Compliant hazmat fulfillment — pick, pack, and ship regulated products with correct packaging, labeling, and docs. Get a quote.",
    keywords: ["hazmat fulfillment", "hazmat logistics (hub)", "hazmat 3pl", "hazmat storage"],
    eyebrowIcon: AlertTriangle,
    eyebrow: "Dangerous Goods",
    h1lead: "Hazmat Fulfillment Done",
    h1gold: "Right",
    heroSub: "Pick, pack, and ship your regulated SKUs with compliant packaging, labeling, and shipping papers every time.",
    ctaLabel: "Get a hazmat fulfillment quote",
    overviewLabel: "What we cover",
    intro: "Fulfilling hazardous materials is where compliance is easiest to get wrong: packaging, labeling, placarding, and carrier selection all have to match the hazard class on every order. Delivery Group handles hazmat fulfillment end to end so each shipment goes out compliant and on time. [[VERIFY: throughput / accuracy %]]",
    sections: [{ h2: "Every order, compliant", body: "We match packaging, labeling, and carrier to each SKU's hazard class, so a mistake doesn't leave your dock. Documentation is produced with the shipment." }, { h2: "Backed by permitted storage", body: "Inventory is held in permitted, segregated space and flows straight into fulfillment — no second vendor, no hand-off." }],
    whyLabel: "Why Delivery Group",
    whyHeading: "A near-zero-competition category most 3PLs won’t touch.",
    whyBullets: ["Compliant packaging & labeling per order", "Correct carrier + placarding by hazard class", "Shipping papers generated automatically"],
    relatedLabel: "Related services",
    related: [{ label: "Hazmat logistics (hub)", href: "/hazmat-logistics" }, { label: "Hazmat 3PL", href: "/hazmat-3pl" }, { label: "Hazmat storage", href: "/hazmat-storage" }, { label: "Pick and pack services", href: "/pick-and-pack-services" }],
    faqs: [{ q: "Do you handle the shipping documentation?", a: "Yes — compliant shipping papers, labels, and placarding are part of the service." }],
    ctaHeading: "Ready to get started?",
    ctaSub: "Share your requirements for hazmat fulfillment and we’ll send a tailored quote.",
    ctaBadge: "All 50 states",
  },
  "hazmat-logistics": {
    slug: "hazmat-logistics",
    keyword: "hazmat logistics",
    metaTitle: "Hazmat Logistics & Dangerous Goods Fulfillment",
    metaDescription: "DOT-compliant hazmat logistics: storage, warehousing, trucking and 3PL fulfillment for dangerous goods across all 50 states. Get a hazmat quote.",
    keywords: ["hazmat logistics", "hazmat storage", "hazmat warehouse", "hazmat trucking companies"],
    eyebrowIcon: AlertTriangle,
    eyebrow: "Dangerous Goods",
    h1lead: "Hazmat Logistics & Dangerous Goods",
    h1gold: "Fulfillment",
    heroSub: "DOT-compliant storage, handling, and last-mile delivery for hazardous materials — one partner for the whole chain.",
    ctaLabel: "Get a hazmat logistics quote",
    overviewLabel: "What we cover",
    intro: "Shipping hazardous materials means UN/DOT classification, proper packaging, placarding, and carriers licensed to move each hazard class. Delivery Group handles hazmat end to end — compliant warehousing, kitting, and delivery across all 50 states — so regulated products move without the compliance risk of piecing together specialists.",
    sections: [{ h2: "Hazmat services we cover", body: "Storage and warehousing of dangerous goods, hazmat 3PL fulfillment, hazmat trucking, and dangerous-goods last-mile delivery — each with the licensing and documentation regulators require." }, { h2: "Why brands choose Delivery Group for hazmat", body: "Near-zero-competition category most 3PLs won't touch: dedicated permitted space, trained handlers, and a single point of accountability from receiving to doorstep." }],
    whyLabel: "Why Delivery Group",
    whyHeading: "A near-zero-competition category most 3PLs won’t touch.",
    whyBullets: ["DOT / IATA / IMDG compliant handling", "Segregated, permitted hazmat storage", "Licensed hazmat carriers, nationwide", "Full documentation & chain-of-custody"],
    relatedLabel: "Related services",
    related: [{ label: "Hazmat storage", href: "/hazmat-storage" }, { label: "Hazmat warehouse", href: "/hazmat-warehouse" }, { label: "Hazmat trucking companies", href: "/hazmat-trucking-companies" }, { label: "Hazmat 3PL", href: "/hazmat-3pl" }, { label: "Hazmat fulfillment", href: "/hazmat-fulfillment" }, { label: "Dangerous goods warehouse", href: "/dangerous-goods-warehouse" }],
    faqs: [{ q: "What hazard classes can Delivery Group handle?", a: "We handle the common commercial hazard classes for consumer and industrial goods; share your UN numbers and SDS and we'll confirm coverage for your SKUs." }, { q: "Do you provide the hazmat shipping documentation?", a: "Yes — we prepare compliant shipping papers, labeling, and placarding as part of the fulfillment service." }],
    ctaHeading: "Ready to get started?",
    ctaSub: "Share your requirements for hazmat logistics and we’ll send a tailored quote.",
    ctaBadge: "All 50 states",
  },
  "hazmat-storage": {
    slug: "hazmat-storage",
    keyword: "hazmat storage",
    metaTitle: "Hazmat Storage | Permitted, Segregated Dangerous-Goods Warehousing",
    metaDescription: "Compliant hazmat storage — permitted, segregated space for hazardous materials with full documentation. Get a hazmat storage quote.",
    keywords: ["hazmat storage", "hazmat logistics (hub)", "hazmat warehouse", "dangerous goods warehouse"],
    eyebrowIcon: AlertTriangle,
    eyebrow: "Dangerous Goods",
    h1lead: "Compliant Hazmat",
    h1gold: "Storage",
    heroSub: "Permitted, segregated storage for hazardous materials — handled by trained staff, documented end to end.",
    ctaLabel: "Get a hazmat storage quote",
    overviewLabel: "What we cover",
    intro: "Storing hazardous materials means permitted space, proper segregation by hazard class, and staff trained to handle regulated goods. Delivery Group provides compliant hazmat storage so your inventory stays within regulation and ready to ship. [[VERIFY: warehouse locations / permitted capacity]]",
    sections: [],
    whyLabel: "Why Delivery Group",
    whyHeading: "A near-zero-competition category most 3PLs won’t touch.",
    whyBullets: ["Permitted hazmat storage space", "Segregation by hazard class", "Trained handlers on site", "Inventory documented & audit-ready"],
    relatedLabel: "Related services",
    related: [{ label: "Hazmat logistics (hub)", href: "/hazmat-logistics" }, { label: "Hazmat warehouse", href: "/hazmat-warehouse" }, { label: "Dangerous goods warehouse", href: "/dangerous-goods-warehouse" }, { label: "Hazmat fulfillment", href: "/hazmat-fulfillment" }],
    faqs: [],
    ctaHeading: "Ready to get started?",
    ctaSub: "Share your requirements for hazmat storage and we’ll send a tailored quote.",
    ctaBadge: "All 50 states",
  },
  "hazmat-trucking-companies": {
    slug: "hazmat-trucking-companies",
    keyword: "hazmat trucking companies",
    metaTitle: "Hazmat Trucking Companies | Licensed DG Carriers Nationwide",
    metaDescription: "DOT-licensed hazmat trucking across all 50 states — placarded loads, trained drivers, full compliance docs. Get a hazmat freight quote.",
    keywords: ["hazmat trucking companies", "hazmat logistics (hub)", "hazmat storage", "hazmat 3pl"],
    eyebrowIcon: AlertTriangle,
    eyebrow: "Dangerous Goods",
    h1lead: "Hazmat Trucking Companies You Can",
    h1gold: "Trust",
    heroSub: "DOT-licensed carriers for hazardous materials — placarded, documented, delivered on time nationwide.",
    ctaLabel: "Get a hazmat freight quote",
    overviewLabel: "What we cover",
    intro: "Moving hazardous materials by road requires carriers licensed for each hazard class, properly placarded equipment, and drivers trained on dangerous-goods handling. Delivery Group runs hazmat freight across all 50 states with full compliance documentation, so your regulated shipments move without the paperwork risk of a general carrier. [[VERIFY: fleet size / states covered]]",
    sections: [],
    whyLabel: "Why Delivery Group",
    whyHeading: "A near-zero-competition category most 3PLs won’t touch.",
    whyBullets: ["DOT-licensed hazmat carriers", "Trained, endorsed hazmat drivers", "Correct placarding & shipping papers"],
    relatedLabel: "Related services",
    related: [{ label: "Hazmat logistics (hub)", href: "/hazmat-logistics" }, { label: "Hazmat storage", href: "/hazmat-storage" }, { label: "Hazmat 3PL", href: "/hazmat-3pl" }, { label: "Dangerous goods warehouse", href: "/dangerous-goods-warehouse" }],
    faqs: [],
    ctaHeading: "Ready to get started?",
    ctaSub: "Share your requirements for hazmat trucking companies and we’ll send a tailored quote.",
    ctaBadge: "All 50 states",
  },
  "hazmat-warehouse": {
    slug: "hazmat-warehouse",
    keyword: "hazmat warehouse",
    metaTitle: "Hazmat Warehouse | Compliant Warehousing for Dangerous Goods",
    metaDescription: "A compliant hazmat warehouse for regulated inventory — permitted, segregated, and wired straight into fulfillment. Get a quote.",
    keywords: ["hazmat warehouse", "hazmat logistics (hub)", "hazmat storage", "hazmat 3pl"],
    eyebrowIcon: AlertTriangle,
    eyebrow: "Dangerous Goods",
    h1lead: "Hazmat Warehouse & Dangerous-Goods",
    h1gold: "Warehousing",
    heroSub: "Regulated inventory kept compliant and ready to ship — receiving, storage, and fulfillment under one roof.",
    ctaLabel: "Get a hazmat warehouse quote",
    overviewLabel: "What we cover",
    intro: "A hazmat warehouse is more than shelf space — it's permitted areas, hazard-class segregation, trained staff, and the documentation regulators expect. Delivery Group warehouses hazardous goods and fulfills them directly, so you don't stitch together a storage vendor and a separate 3PL. [[VERIFY: warehouse footprint / locations]]",
    sections: [],
    whyLabel: "Why Delivery Group",
    whyHeading: "A near-zero-competition category most 3PLs won’t touch.",
    whyBullets: ["Permitted, segregated warehousing", "Trained dangerous-goods staff", "Receiving → storage → fulfillment in one place", "Full compliance documentation"],
    relatedLabel: "Related services",
    related: [{ label: "Hazmat logistics (hub)", href: "/hazmat-logistics" }, { label: "Hazmat storage", href: "/hazmat-storage" }, { label: "Hazmat 3PL", href: "/hazmat-3pl" }, { label: "Dangerous goods warehouse", href: "/dangerous-goods-warehouse" }],
    faqs: [{ q: "Do you fulfill orders out of the hazmat warehouse?", a: "Yes — we pick, pack, and ship regulated goods directly from the same compliant facility." }],
    ctaHeading: "Ready to get started?",
    ctaSub: "Share your requirements for hazmat warehouse and we’ll send a tailored quote.",
    ctaBadge: "All 50 states",
  },
  "kitting-services": {
    slug: "kitting-services",
    keyword: "kitting services",
    metaTitle: "Kitting Services | Assembly, Bundling & Subscription Kits",
    metaDescription: "Kitting and assembly services — bundles, subscription boxes, and multi-SKU kits assembled and shipped accurately. Get a kitting quote.",
    keywords: ["kitting services", "fulfillment center (hub)", "pick and pack services", "subscription box fulfillment"],
    eyebrowIcon: Package,
    eyebrow: "Fulfillment",
    h1lead: "Kitting & Assembly",
    h1gold: "Services",
    heroSub: "Turn loose SKUs into ready-to-ship kits — bundles, subscription boxes, and promo sets assembled accurately.",
    ctaLabel: "Get a kitting quote",
    overviewLabel: "What we cover",
    intro: "Kitting takes multiple SKUs and combines them into a single ship-ready unit — subscription boxes, product bundles, retail displays, promo packs. Delivery Group assembles and stores your kits and ships them on demand, so bundling never slows your fulfillment down. [[VERIFY: kitting capacity / turnaround]]",
    sections: [{ h2: "Kitting the way you need it", body: "We can pre-assemble kits and hold them as a single SKU, or build them on demand as orders arrive — whichever keeps costs and speed where you want them." }, { h2: "Built into fulfillment", body: "Kitting runs inside the same operation that stores and ships your inventory — no shuttling product between vendors." }],
    whyLabel: "Why Delivery Group",
    whyHeading: "Fulfillment that scales from startup to enterprise volume.",
    whyBullets: ["Bundles, kits & subscription boxes", "Custom inserts & branded packaging", "Pre-kitted or assembled on demand", "Accurate, tracked assembly"],
    relatedLabel: "Related services",
    related: [{ label: "Fulfillment center (hub)", href: "/fulfillment-center" }, { label: "Pick and pack services", href: "/pick-and-pack-services" }, { label: "Subscription box fulfillment", href: "/solutions/subscription-boxes" }, { label: "Fulfillment warehouse", href: "/fulfillment-warehouse" }],
    faqs: [{ q: "Can you assemble subscription boxes?", a: "Yes — recurring subscription kits with custom inserts and branded packaging are a core use case." }],
    ctaHeading: "Ready to get started?",
    ctaSub: "Share your requirements for kitting services and we’ll send a tailored quote.",
    ctaBadge: "All 50 states",
  },
  "medical-courier": {
    slug: "medical-courier",
    keyword: "medical courier",
    metaTitle: "Medical Courier Services | Specimen & Pharma Delivery",
    metaDescription: "Medical courier services — compliant, tracked delivery of specimens, pharmaceuticals, and medical supplies with chain of custody. Get a quote.",
    keywords: ["medical courier", "courier services (hub)", "same day courier", "rush delivery"],
    eyebrowIcon: Truck,
    eyebrow: "Courier & Delivery",
    h1lead: "Medical Courier",
    h1gold: "Services",
    heroSub: "Compliant, tracked delivery for specimens, pharmaceuticals, and medical supplies — with chain of custody.",
    ctaLabel: "Get a medical courier quote",
    overviewLabel: "What we cover",
    intro: "Medical deliveries carry requirements ordinary couriers don't meet: temperature control, chain of custody, HIPAA-aware handling, and reliable timing. Delivery Group provides medical courier services with trained drivers and documented custody, so labs, clinics, and pharmacies get dependable, compliant transport. [[VERIFY: certifications — HIPAA/temperature/CLIA handling]]",
    sections: [],
    whyLabel: "Why Delivery Group",
    whyHeading: "One partner for every delivery urgency.",
    whyBullets: ["Specimen, pharma & supply transport", "Chain of custody & documentation"],
    relatedLabel: "Related services",
    related: [{ label: "Courier services (hub)", href: "/courier-services" }, { label: "Same day courier", href: "/same-day-courier" }, { label: "Rush delivery", href: "/rush-delivery" }, { label: "Healthcare logistics", href: "/industries/healthcare" }],
    faqs: [],
    ctaHeading: "Ready to get started?",
    ctaSub: "Share your requirements for medical courier and we’ll send a tailored quote.",
    ctaBadge: "All 50 states",
  },
  "on-demand-delivery": {
    slug: "on-demand-delivery",
    keyword: "on demand delivery",
    metaTitle: "On-Demand Delivery Services for Business",
    metaDescription: "On-demand delivery for business — request a driver when you need one, with live tracking and proof of delivery. Get a quote.",
    keywords: ["on demand delivery", "courier services (hub)", "same day courier", "rush delivery"],
    eyebrowIcon: Truck,
    eyebrow: "Courier & Delivery",
    h1lead: "On-Demand",
    h1gold: "Delivery",
    heroSub: "A delivery driver when you need one — request, track, and deliver, without owning a fleet.",
    ctaLabel: "Get an on-demand delivery quote",
    overviewLabel: "What we cover",
    intro: "On-demand delivery gives your business a driver the moment you need one — no fleet to run, no dispatchers to hire. Delivery Group provides on-demand delivery with live tracking and proof of delivery, whether it's a one-off or a daily need. [[VERIFY: service areas / response time]]",
    sections: [{ h2: "Delivery capacity without the fleet", body: "Scale delivery up and down with demand — pay per delivery instead of carrying vehicles and drivers you don't always need." }],
    whyLabel: "Why Delivery Group",
    whyHeading: "One partner for every delivery urgency.",
    whyBullets: ["Request a driver on demand", "Live tracking + proof of delivery", "No fleet or dispatch to run", "One-off or recurring"],
    relatedLabel: "Related services",
    related: [{ label: "Courier services (hub)", href: "/courier-services" }, { label: "Same day courier", href: "/same-day-courier" }, { label: "Rush delivery", href: "/rush-delivery" }, { label: "Last-mile delivery", href: "/services/last-mile-delivery" }],
    faqs: [],
    ctaHeading: "Ready to get started?",
    ctaSub: "Share your requirements for on demand delivery and we’ll send a tailored quote.",
    ctaBadge: "All 50 states",
  },
  "pick-and-pack-services": {
    slug: "pick-and-pack-services",
    keyword: "pick and pack services",
    metaTitle: "Pick and Pack Services | Fast, Accurate Order Fulfillment",
    metaDescription: "Outsourced pick and pack fulfillment with 99.4% accuracy across 50 states. Same-day pick, branded packing, real-time inventory. Get a quote.",
    keywords: ["pick and pack services", "order fulfillment center (hub)", "kitting services", "fulfillment warehouse"],
    eyebrowIcon: Package,
    eyebrow: "Fulfillment",
    h1lead: "Pick and Pack",
    h1gold: "Services",
    heroSub: "Accurate, branded order fulfillment that scales with your volume — pick, pack, ship from one partner.",
    ctaLabel: "Get a pick and pack quote",
    overviewLabel: "What we cover",
    intro: "Pick and pack is where fulfillment is won or lost: the right item, packed right, out the door on time. Delivery Group picks, packs, and ships your orders with [[VERIFY: 99.4%]] on-time performance and real-time inventory visibility, from facilities positioned to reach the whole country fast.",
    sections: [{ h2: "How our pick and pack process works", body: "Receive & store your SKUs, pick against each incoming order, pack to your spec (branded inserts, kitting, fragile handling), then hand off to the optimal carrier — all tracked end to end." }],
    whyLabel: "Why Delivery Group",
    whyHeading: "Fulfillment that scales from startup to enterprise volume.",
    whyBullets: [],
    relatedLabel: "Related services",
    related: [{ label: "Order fulfillment center (hub)", href: "/fulfillment-center" }, { label: "Kitting services", href: "/kitting-services" }, { label: "Fulfillment warehouse", href: "/fulfillment-warehouse" }, { label: "3PL fulfillment", href: "/3pl-fulfillment" }],
    faqs: [{ q: "What does pick and pack cost?", a: "Pricing is per order plus storage; share your SKU count and monthly volume for an exact quote." }, { q: "Can you use our own branded packaging?", a: "Yes — we pack with your boxes, inserts, and kitting to keep the unboxing on-brand." }],
    ctaHeading: "Ready to get started?",
    ctaSub: "Share your requirements for pick and pack services and we’ll send a tailored quote.",
    ctaBadge: "All 50 states",
  },
  "returns-management": {
    slug: "returns-management",
    keyword: "returns management",
    metaTitle: "Returns Management Services | Reverse Logistics 3PL",
    metaDescription: "Outsourced returns management — receive, inspect, restock, and refurbish returns fast so inventory and cash come back sooner. Get a quote.",
    keywords: ["returns management", "reverse logistics services", "ecommerce returns management", "returns processing"],
    eyebrowIcon: RefreshCw,
    eyebrow: "Reverse Logistics",
    h1lead: "Returns Management",
    h1gold: "Services",
    heroSub: "Turn returns from a cost center into recovered inventory — received, inspected, and restocked fast.",
    ctaLabel: "Get a returns management quote",
    overviewLabel: "What we cover",
    intro: "Returns are inevitable; losing money on them isn't. Delivery Group manages the whole reverse-logistics flow — receiving, inspection, grading, restocking, and disposition — so sellable inventory goes back on the shelf quickly and you recover value instead of writing it off. [[VERIFY: return processing time / restock rate]]",
    sections: [{ h2: "A defined disposition for every return", body: "Each return is inspected and routed by your rules — restock, refurbish, liquidate, or dispose — so nothing sits in limbo and good stock sells again fast." }],
    whyLabel: "Why Delivery Group",
    whyHeading: "Turn returns from a cost center into recovered value.",
    whyBullets: ["Receive, inspect & grade returns", "Fast restock of sellable items", "Refurbish / repackage / dispose by rule", "Reporting on return reasons"],
    relatedLabel: "Related services",
    related: [{ label: "Reverse logistics services", href: "/reverse-logistics-services" }, { label: "Ecommerce returns management", href: "/ecommerce-returns-management" }, { label: "Returns processing", href: "/returns-processing" }, { label: "Ecommerce returns (guide)", href: "/blog/ecommerce-returns-management" }],
    faqs: [],
    ctaHeading: "Ready to get started?",
    ctaSub: "Share your requirements for returns management and we’ll send a tailored quote.",
    ctaBadge: "All 50 states",
  },
  "returns-processing": {
    slug: "returns-processing",
    keyword: "returns processing",
    metaTitle: "Returns Processing Services | Inspect, Grade & Restock",
    metaDescription: "Returns processing that clears the backlog — inspect, grade, restock, and disposition returns accurately at volume. Get a quote.",
    keywords: ["returns processing", "returns management (hub)", "reverse logistics services", "ecommerce returns management"],
    eyebrowIcon: RefreshCw,
    eyebrow: "Reverse Logistics",
    h1lead: "Returns Processing",
    h1gold: "Services",
    heroSub: "Clear the returns backlog — inspect, grade, and restock at volume with accurate disposition.",
    ctaLabel: "Get a returns processing quote",
    overviewLabel: "What we cover",
    intro: "Returns processing is the hands-on work of getting returned goods inspected, graded, and back into the right place. Delivery Group processes returns accurately at volume, so a pile of returned boxes becomes restocked inventory and clean data instead of a growing backlog. [[VERIFY: processing capacity]]",
    sections: [{ h2: "Consistent grading at scale", body: "Every return is inspected and graded to the same standard, so restock decisions are reliable and customers who get restocked items aren't disappointed." }],
    whyLabel: "Why Delivery Group",
    whyHeading: "Turn returns from a cost center into recovered value.",
    whyBullets: ["High-volume return intake", "Consistent inspection & grading", "Accurate disposition", "Clean return data"],
    relatedLabel: "Related services",
    related: [{ label: "Returns management (hub)", href: "/returns-management" }, { label: "Reverse logistics services", href: "/reverse-logistics-services" }, { label: "Ecommerce returns management", href: "/ecommerce-returns-management" }, { label: "Fulfillment warehouse", href: "/fulfillment-warehouse" }],
    faqs: [],
    ctaHeading: "Ready to get started?",
    ctaSub: "Share your requirements for returns processing and we’ll send a tailored quote.",
    ctaBadge: "All 50 states",
  },
  "reverse-logistics-services": {
    slug: "reverse-logistics-services",
    keyword: "reverse logistics services",
    metaTitle: "Reverse Logistics Services | Returns, Refurb & Recovery",
    metaDescription: "Reverse logistics services — returns intake, inspection, refurbishment, and value recovery from one 3PL. Get a quote.",
    keywords: ["reverse logistics services", "returns management (hub)", "ecommerce returns management", "returns processing"],
    eyebrowIcon: RefreshCw,
    eyebrow: "Reverse Logistics",
    h1lead: "Reverse Logistics",
    h1gold: "Services",
    heroSub: "The full backward flow of goods — returns, refurbishment, and recovery — run by one accountable partner.",
    ctaLabel: "Get a reverse logistics quote",
    overviewLabel: "What we cover",
    intro: "Reverse logistics is everything that happens after a product comes back: intake, inspection, refurbishment, restocking, recycling, and disposal. As a reverse logistics company built into a full 3PL, Delivery Group manages that entire flow so value is recovered and sellable stock returns to inventory fast. [[VERIFY: recovery rates / capabilities]]",
    sections: [{ h2: "Why one partner for both directions", body: "Because we also do your outbound fulfillment, recovered stock goes straight back into the same inventory that ships orders — no transfers between vendors." }],
    whyLabel: "Why Delivery Group",
    whyHeading: "Turn returns from a cost center into recovered value.",
    whyBullets: ["End-to-end reverse flow", "Inspection, grading & refurbishment", "Restock, recycle or dispose", "One partner with forward logistics too"],
    relatedLabel: "Related services",
    related: [{ label: "Returns management (hub)", href: "/returns-management" }, { label: "Ecommerce returns management", href: "/ecommerce-returns-management" }, { label: "Returns processing", href: "/returns-processing" }, { label: "3PL fulfillment", href: "/3pl-fulfillment" }],
    faqs: [{ q: "Are you a reverse logistics company or a full 3PL?", a: "Both — reverse logistics runs inside our full 3PL, so forward and reverse flows share one inventory and one system." }],
    ctaHeading: "Ready to get started?",
    ctaSub: "Share your requirements for reverse logistics services and we’ll send a tailored quote.",
    ctaBadge: "All 50 states",
  },
  "rush-delivery": {
    slug: "rush-delivery",
    keyword: "rush delivery",
    metaTitle: "Rush Delivery Services | Urgent Same-Day Courier",
    metaDescription: "Rush delivery for time-critical shipments — fastest available dispatch, direct routing, tracking and proof of delivery. Get a quote.",
    keywords: ["rush delivery", "courier services (hub)", "same day courier", "on-demand delivery"],
    eyebrowIcon: Truck,
    eyebrow: "Courier & Delivery",
    h1lead: "Rush Delivery",
    h1gold: "Services",
    heroSub: "When it has to be there now — fastest-available dispatch, direct routing, tracked the whole way.",
    ctaLabel: "Get a rush delivery quote",
    overviewLabel: "What we cover",
    intro: "Rush delivery is for the shipments that can't wait: a part that stops a line, a document that closes a deal, a sample that lands a client. Delivery Group dispatches rush deliveries with the fastest available driver and direct routing — no consolidation, no detours. [[VERIFY: coverage / dispatch time]]",
    sections: [{ h2: "Direct, not consolidated", body: "A rush job goes straight from pickup to destination — no shared route, no extra stops — so it arrives as fast as physically possible." }],
    whyLabel: "Why Delivery Group",
    whyHeading: "One partner for every delivery urgency.",
    whyBullets: ["Fastest-available dispatch", "Direct, dedicated routing", "Live tracking + proof of delivery"],
    relatedLabel: "Related services",
    related: [{ label: "Courier services (hub)", href: "/courier-services" }, { label: "Same day courier", href: "/same-day-courier" }, { label: "On-demand delivery", href: "/on-demand-delivery" }, { label: "Expedited shipping", href: "/services/expedited-shipping" }],
    faqs: [{ q: "How fast is rush delivery?", a: "Fastest-available dispatch with direct routing; timing depends on distance — share pickup and destination for an exact ETA." }],
    ctaHeading: "Ready to get started?",
    ctaSub: "Share your requirements for rush delivery and we’ll send a tailored quote.",
    ctaBadge: "All 50 states",
  },
  "same-day-courier": {
    slug: "same-day-courier",
    keyword: "same day courier",
    metaTitle: "Same Day Courier Services for Business",
    metaDescription: "Reliable same-day courier for business — urgent local pickups and deliveries with tracking and proof of delivery. Get a quote.",
    keywords: ["same day courier", "courier services (hub)", "white glove delivery", "last-mile delivery"],
    eyebrowIcon: Truck,
    eyebrow: "Courier & Delivery",
    h1lead: "Same Day Courier",
    h1gold: "Services",
    heroSub: "Urgent pickups and deliveries handled the same day — with live tracking and proof of delivery.",
    ctaLabel: "Get a same day courier quote",
    overviewLabel: "What we cover",
    intro: "When a shipment has to be there today, a same-day courier is the difference between a kept promise and a lost account. Delivery Group runs same-day courier service for businesses — urgent documents, parts, samples, and time-critical goods — with tracking and proof of delivery on every job. [[VERIFY: service areas / cut-off times]]",
    sections: [],
    whyLabel: "Why Delivery Group",
    whyHeading: "One partner for every delivery urgency.",
    whyBullets: ["Same-day local pickup & delivery", "Live tracking + proof of delivery", "Dedicated and scheduled routes", "Business accounts & recurring runs"],
    relatedLabel: "Related services",
    related: [{ label: "Courier services (hub)", href: "/courier-services" }, { label: "White glove delivery", href: "/white-glove-delivery" }, { label: "Last-mile delivery", href: "/services/last-mile-delivery" }, { label: "Expedited shipping", href: "/services/expedited-shipping" }],
    faqs: [],
    ctaHeading: "Ready to get started?",
    ctaSub: "Share your requirements for same day courier and we’ll send a tailored quote.",
    ctaBadge: "All 50 states",
  },
  "small-business-fulfillment": {
    slug: "small-business-fulfillment",
    keyword: "small business fulfillment",
    metaTitle: "Small Business Fulfillment | Affordable 3PL for Growing Brands",
    metaDescription: "Order fulfillment built for small businesses — no minimums headaches, transparent per-order pricing, room to scale. Get a quote.",
    keywords: ["small business fulfillment", "fulfillment center (hub)", "3pl fulfillment", "pick and pack services"],
    eyebrowIcon: Package,
    eyebrow: "Fulfillment",
    h1lead: "Small Business",
    h1gold: "Fulfillment",
    heroSub: "3PL fulfillment sized for growing brands — transparent pricing, real support, and room to scale.",
    ctaLabel: "Get a fulfillment quote",
    overviewLabel: "What we cover",
    intro: "Small businesses get squeezed by 3PLs built for enterprise volume — high minimums, opaque fees, no support. Delivery Group offers small business fulfillment with transparent per-order pricing and hands-on onboarding, so a growing brand ships like a big one from day one. [[VERIFY: minimums / onboarding time]]",
    sections: [{ h2: "3PL that fits a small business", body: "Store, pick, pack, and ship without enterprise-only contracts. As your order count grows, capacity grows with it — same partner, no migration." }],
    whyLabel: "Why Delivery Group",
    whyHeading: "Fulfillment that scales from startup to enterprise volume.",
    whyBullets: ["Transparent per-order pricing", "Low/flexible minimums", "Hands-on onboarding & support", "Scales as you grow"],
    relatedLabel: "Related services",
    related: [{ label: "Fulfillment center (hub)", href: "/fulfillment-center" }, { label: "3PL fulfillment", href: "/3pl-fulfillment" }, { label: "Pick and pack services", href: "/pick-and-pack-services" }, { label: "Etsy fulfillment", href: "/etsy-fulfillment" }],
    faqs: [],
    ctaHeading: "Ready to get started?",
    ctaSub: "Share your requirements for small business fulfillment and we’ll send a tailored quote.",
    ctaBadge: "All 50 states",
  },
  "tiktok-shop-fulfillment": {
    slug: "tiktok-shop-fulfillment",
    keyword: "tiktok shop fulfillment",
    metaTitle: "TikTok Shop Fulfillment | Handle Viral Spikes",
    metaDescription: "TikTok Shop fulfillment that keeps up with viral demand — fast pick/pack, real-time inventory, and shipping that scales. Get a quote.",
    keywords: ["tiktok shop fulfillment", "fulfillment center (hub)", "pick and pack services", "small business fulfillment"],
    eyebrowIcon: Package,
    eyebrow: "Fulfillment",
    h1lead: "TikTok Shop",
    h1gold: "Fulfillment",
    heroSub: "Ship viral demand without falling behind — fast fulfillment that scales the moment a video takes off.",
    ctaLabel: "Get a fulfillment quote",
    overviewLabel: "What we cover",
    intro: "TikTok Shop rewards sellers who can ship fast when a video goes viral — and punishes those who can't. Delivery Group fulfills TikTok Shop orders with same-day pick cut-offs and capacity that absorbs sudden spikes, so a hit doesn't turn into late shipments and bad reviews. [[VERIFY: TikTok Shop integration details]]",
    sections: [],
    whyLabel: "Why Delivery Group",
    whyHeading: "Fulfillment that scales from startup to enterprise volume.",
    whyBullets: ["Handles viral demand spikes", "Same-day pick cut-offs", "Real-time inventory sync", "Fast, tracked nationwide shipping"],
    relatedLabel: "Related services",
    related: [{ label: "Fulfillment center (hub)", href: "/fulfillment-center" }, { label: "Pick and pack services", href: "/pick-and-pack-services" }, { label: "Small business fulfillment", href: "/small-business-fulfillment" }, { label: "Same day courier", href: "/same-day-courier" }],
    faqs: [],
    ctaHeading: "Ready to get started?",
    ctaSub: "Share your requirements for tiktok shop fulfillment and we’ll send a tailored quote.",
    ctaBadge: "All 50 states",
  },
  "white-glove-delivery": {
    slug: "white-glove-delivery",
    keyword: "white glove delivery",
    metaTitle: "White Glove Delivery Services | Inside Delivery & Setup",
    metaDescription: "White glove delivery for high-value, fragile, and oversized items — inside delivery, placement, setup, and debris removal. Get a quote.",
    keywords: ["white glove delivery", "courier services (hub)", "same day courier", "last-mile delivery"],
    eyebrowIcon: Truck,
    eyebrow: "Courier & Delivery",
    h1lead: "White Glove Delivery",
    h1gold: "Services",
    heroSub: "Premium delivery for high-value, fragile, and oversized items — carried in, placed, set up, and cleaned up.",
    ctaLabel: "Get a white glove delivery quote",
    overviewLabel: "What we cover",
    intro: "White glove delivery is the opposite of leaving a box at the curb: trained two-person teams bring the item inside, place it where it belongs, set it up, and remove the packaging. Delivery Group provides white glove service for the products where the delivery experience is part of the brand. [[VERIFY: coverage / scheduling windows]]",
    sections: [{ h2: "When white glove is worth it", body: "Furniture, fitness equipment, medical devices, electronics, and premium DTC goods — anything heavy, fragile, or high-value where a dropped box means a return and a bad review." }],
    whyLabel: "Why Delivery Group",
    whyHeading: "One partner for every delivery urgency.",
    whyBullets: ["Two-person, in-home/in-office delivery", "Placement, assembly & setup", "Packaging & debris removal", "Scheduled delivery windows"],
    relatedLabel: "Related services",
    related: [{ label: "Courier services (hub)", href: "/courier-services" }, { label: "Same day courier", href: "/same-day-courier" }, { label: "Last-mile delivery", href: "/services/last-mile-delivery" }, { label: "Oversized solutions", href: "/solutions/oversized" }],
    faqs: [{ q: "What does white glove delivery include?", a: "Inside delivery, placement, assembly/setup where applicable, and removal of packaging and debris." }],
    ctaHeading: "Ready to get started?",
    ctaSub: "Share your requirements for white glove delivery and we’ll send a tailored quote.",
    ctaBadge: "All 50 states",
  },
}
