export interface Location {
  slug: string
  city: string
  state: string
  stateAbbr: string
  metro: string
  description: string
  stats: { value: string; label: string }[]
  services: string[]
}

export const locations: Location[] = [
  { slug: "new-york-ny", city: "New York", state: "New York", stateAbbr: "NY", metro: "New York Metro", description: "Serving the New York metropolitan area with comprehensive last-mile delivery across all five boroughs, Long Island, and New Jersey.", stats: [{ value: "Next Day", label: "Available" }, { value: "99.3%", label: "On-Time Rate" }, { value: "2M+", label: "Annual Deliveries" }], services: ["Last-Mile Delivery"] },
  { slug: "los-angeles-ca", city: "Los Angeles", state: "California", stateAbbr: "CA", metro: "Los Angeles Metro", description: "End-to-end delivery solutions across the greater Los Angeles area, from the San Fernando Valley to Long Beach.", stats: [{ value: "Next Day", label: "Available" }, { value: "99.1%", label: "On-Time Rate" }, { value: "1.8M+", label: "Annual Deliveries" }], services: ["Last-Mile Delivery"] },
  { slug: "chicago-il", city: "Chicago", state: "Illinois", stateAbbr: "IL", metro: "Chicago Metro", description: "Strategic logistics hub serving the Chicago metro and greater Midwest region with reliable last-mile and freight services.", stats: [{ value: "Next Day", label: "Available" }, { value: "99.4%", label: "On-Time Rate" }, { value: "1.5M+", label: "Annual Deliveries" }], services: ["Last-Mile Delivery"] },
  { slug: "houston-tx", city: "Houston", state: "Texas", stateAbbr: "TX", metro: "Houston Metro", description: "Comprehensive delivery services across the Houston metro area, serving both residential and commercial customers throughout Harris County and beyond.", stats: [{ value: "Next Day", label: "Available" }, { value: "99.2%", label: "On-Time Rate" }, { value: "1.2M+", label: "Annual Deliveries" }], services: ["Last-Mile Delivery"] },
  { slug: "phoenix-az", city: "Phoenix", state: "Arizona", stateAbbr: "AZ", metro: "Phoenix Metro", description: "Serving Phoenix and the greater Valley of the Sun with scalable delivery solutions built for Arizona's rapid growth.", stats: [{ value: "Next Day", label: "Available" }, { value: "99.0%", label: "On-Time Rate" }, { value: "900K+", label: "Annual Deliveries" }], services: ["Last-Mile Delivery"] },
  { slug: "philadelphia-pa", city: "Philadelphia", state: "Pennsylvania", stateAbbr: "PA", metro: "Philadelphia Metro", description: "Delivery solutions across Philadelphia and the Delaware Valley, with connections to New Jersey and Delaware.", stats: [{ value: "Next Day", label: "Available" }, { value: "99.3%", label: "On-Time Rate" }, { value: "850K+", label: "Annual Deliveries" }], services: ["Last-Mile Delivery"] },
  { slug: "san-antonio-tx", city: "San Antonio", state: "Texas", stateAbbr: "TX", metro: "San Antonio Metro", description: "Reliable delivery services across San Antonio and the surrounding Hill Country region.", stats: [{ value: "Next Day", label: "Available" }, { value: "99.1%", label: "On-Time Rate" }, { value: "600K+", label: "Annual Deliveries" }], services: ["Last-Mile Delivery", "Expedited Shipping"] },
  { slug: "san-diego-ca", city: "San Diego", state: "California", stateAbbr: "CA", metro: "San Diego Metro", description: "Comprehensive delivery coverage across San Diego County, from downtown to the inland communities.", stats: [{ value: "Next Day", label: "Available" }, { value: "99.2%", label: "On-Time Rate" }, { value: "700K+", label: "Annual Deliveries" }], services: ["Last-Mile Delivery"] },
  { slug: "dallas-tx", city: "Dallas", state: "Texas", stateAbbr: "TX", metro: "Dallas-Fort Worth Metroplex", description: "Serving the Dallas-Fort Worth Metroplex with premium delivery solutions across one of the fastest-growing markets in the United States.", stats: [{ value: "Next Day", label: "Available" }, { value: "99.4%", label: "On-Time Rate" }, { value: "1.3M+", label: "Annual Deliveries" }], services: ["Last-Mile Delivery"] },
  { slug: "san-jose-ca", city: "San Jose", state: "California", stateAbbr: "CA", metro: "Silicon Valley", description: "Technology-forward delivery solutions for Silicon Valley businesses and consumers.", stats: [{ value: "Next Day", label: "Available" }, { value: "99.5%", label: "On-Time Rate" }, { value: "750K+", label: "Annual Deliveries" }], services: ["Last-Mile Delivery"] },
  { slug: "austin-tx", city: "Austin", state: "Texas", stateAbbr: "TX", metro: "Austin Metro", description: "Rapidly expanding delivery network across Austin and the greater Central Texas region.", stats: [{ value: "Next Day", label: "Available" }, { value: "99.3%", label: "On-Time Rate" }, { value: "800K+", label: "Annual Deliveries" }], services: ["Last-Mile Delivery"] },
  { slug: "jacksonville-fl", city: "Jacksonville", state: "Florida", stateAbbr: "FL", metro: "Jacksonville Metro", description: "Serving Jacksonville and Northeast Florida with reliable last-mile delivery solutions.", stats: [{ value: "Next Day", label: "Available" }, { value: "99.0%", label: "On-Time Rate" }, { value: "500K+", label: "Annual Deliveries" }], services: ["Last-Mile Delivery", "Expedited Shipping"] },
  { slug: "fort-worth-tx", city: "Fort Worth", state: "Texas", stateAbbr: "TX", metro: "Dallas-Fort Worth Metroplex", description: "Comprehensive delivery services across Fort Worth and Western Tarrant County.", stats: [{ value: "Next Day", label: "Available" }, { value: "99.2%", label: "On-Time Rate" }, { value: "600K+", label: "Annual Deliveries" }], services: ["Last-Mile Delivery"] },
  { slug: "columbus-oh", city: "Columbus", state: "Ohio", stateAbbr: "OH", metro: "Columbus Metro", description: "Centrally located Columbus operations serving Ohio and the broader Midwest with efficient delivery services.", stats: [{ value: "Next Day", label: "Available" }, { value: "99.4%", label: "On-Time Rate" }, { value: "650K+", label: "Annual Deliveries" }], services: ["Last-Mile Delivery"] },
  { slug: "charlotte-nc", city: "Charlotte", state: "North Carolina", stateAbbr: "NC", metro: "Charlotte Metro", description: "Delivery solutions across the Charlotte metro and the greater Piedmont region of North Carolina.", stats: [{ value: "Next Day", label: "Available" }, { value: "99.1%", label: "On-Time Rate" }, { value: "550K+", label: "Annual Deliveries" }], services: ["Last-Mile Delivery"] },
  { slug: "indianapolis-in", city: "Indianapolis", state: "Indiana", stateAbbr: "IN", metro: "Indianapolis Metro", description: "Indianapolis delivery services leveraging the city's strategic position as a national logistics hub.", stats: [{ value: "Next Day", label: "Available" }, { value: "99.5%", label: "On-Time Rate" }, { value: "700K+", label: "Annual Deliveries" }], services: ["Last-Mile Delivery"] },
  { slug: "san-francisco-ca", city: "San Francisco", state: "California", stateAbbr: "CA", metro: "Bay Area", description: "Premium delivery solutions across San Francisco and the greater Bay Area, with expertise in urban last-mile delivery.", stats: [{ value: "Next Day", label: "Available" }, { value: "99.4%", label: "On-Time Rate" }, { value: "950K+", label: "Annual Deliveries" }], services: ["Last-Mile Delivery"] },
  { slug: "seattle-wa", city: "Seattle", state: "Washington", stateAbbr: "WA", metro: "Seattle Metro", description: "Comprehensive delivery coverage across Seattle and the greater Puget Sound region.", stats: [{ value: "Next Day", label: "Available" }, { value: "99.3%", label: "On-Time Rate" }, { value: "800K+", label: "Annual Deliveries" }], services: ["Last-Mile Delivery"] },
  { slug: "denver-co", city: "Denver", state: "Colorado", stateAbbr: "CO", metro: "Denver Metro", description: "Delivery services across Denver and the Front Range, with specialized capabilities for mountain community access.", stats: [{ value: "Next Day", label: "Available" }, { value: "99.2%", label: "On-Time Rate" }, { value: "700K+", label: "Annual Deliveries" }], services: ["Last-Mile Delivery"] },
  { slug: "washington-dc", city: "Washington", state: "District of Columbia", stateAbbr: "DC", metro: "Washington DC Metro", description: "Serving the nation's capital and the greater DMV area across DC, Maryland, and Virginia.", stats: [{ value: "Next Day", label: "Available" }, { value: "99.5%", label: "On-Time Rate" }, { value: "1.1M+", label: "Annual Deliveries" }], services: ["Last-Mile Delivery"] },
  { slug: "nashville-tn", city: "Nashville", state: "Tennessee", stateAbbr: "TN", metro: "Nashville Metro", description: "Fast-growing Nashville delivery network serving Middle Tennessee's expanding metropolitan area.", stats: [{ value: "Next Day", label: "Available" }, { value: "99.2%", label: "On-Time Rate" }, { value: "550K+", label: "Annual Deliveries" }], services: ["Last-Mile Delivery"] },
  { slug: "el-paso-tx", city: "El Paso", state: "Texas", stateAbbr: "TX", metro: "El Paso Metro", description: "Delivery solutions across El Paso and the Borderplex region, with cross-border logistics expertise.", stats: [{ value: "Next Day", label: "Available" }, { value: "98.9%", label: "On-Time Rate" }, { value: "350K+", label: "Annual Deliveries" }], services: ["Last-Mile Delivery", "Expedited Shipping"] },
  { slug: "oklahoma-city-ok", city: "Oklahoma City", state: "Oklahoma", stateAbbr: "OK", metro: "Oklahoma City Metro", description: "Reliable delivery services across Oklahoma City and central Oklahoma.", stats: [{ value: "Next Day", label: "Available" }, { value: "99.0%", label: "On-Time Rate" }, { value: "400K+", label: "Annual Deliveries" }], services: ["Last-Mile Delivery", "Expedited Shipping"] },
  { slug: "boston-ma", city: "Boston", state: "Massachusetts", stateAbbr: "MA", metro: "Greater Boston", description: "Premium delivery services across Greater Boston and throughout New England.", stats: [{ value: "Next Day", label: "Available" }, { value: "99.4%", label: "On-Time Rate" }, { value: "850K+", label: "Annual Deliveries" }], services: ["Last-Mile Delivery"] },
  { slug: "portland-or", city: "Portland", state: "Oregon", stateAbbr: "OR", metro: "Portland Metro", description: "Delivery solutions across the Portland metropolitan area and the greater Pacific Northwest.", stats: [{ value: "Next Day", label: "Available" }, { value: "99.1%", label: "On-Time Rate" }, { value: "600K+", label: "Annual Deliveries" }], services: ["Last-Mile Delivery"] },
  { slug: "las-vegas-nv", city: "Las Vegas", state: "Nevada", stateAbbr: "NV", metro: "Las Vegas Valley", description: "Comprehensive delivery capabilities across Las Vegas and the greater Nevada region.", stats: [{ value: "Next Day", label: "Available" }, { value: "99.3%", label: "On-Time Rate" }, { value: "700K+", label: "Annual Deliveries" }], services: ["Last-Mile Delivery"] },
  { slug: "memphis-tn", city: "Memphis", state: "Tennessee", stateAbbr: "TN", metro: "Memphis Metro", description: "Memphis operations leverage the city's position as a global logistics hub for accelerated delivery services.", stats: [{ value: "Next Day", label: "Available" }, { value: "99.5%", label: "On-Time Rate" }, { value: "800K+", label: "Annual Deliveries" }], services: ["Last-Mile Delivery"] },
  { slug: "louisville-ky", city: "Louisville", state: "Kentucky", stateAbbr: "KY", metro: "Louisville Metro", description: "Strategic Louisville operations serving Kentucky and the greater mid-South region.", stats: [{ value: "Next Day", label: "Available" }, { value: "99.4%", label: "On-Time Rate" }, { value: "550K+", label: "Annual Deliveries" }], services: ["Last-Mile Delivery"] },
  { slug: "baltimore-md", city: "Baltimore", state: "Maryland", stateAbbr: "MD", metro: "Baltimore Metro", description: "Comprehensive delivery solutions across Baltimore and the greater Maryland region.", stats: [{ value: "Next Day", label: "Available" }, { value: "99.2%", label: "On-Time Rate" }, { value: "600K+", label: "Annual Deliveries" }], services: ["Last-Mile Delivery"] },
  { slug: "milwaukee-wi", city: "Milwaukee", state: "Wisconsin", stateAbbr: "WI", metro: "Milwaukee Metro", description: "Reliable delivery services across Milwaukee and southeastern Wisconsin.", stats: [{ value: "Next Day", label: "Available" }, { value: "99.1%", label: "On-Time Rate" }, { value: "450K+", label: "Annual Deliveries" }], services: ["Last-Mile Delivery", "Expedited Shipping"] },
  { slug: "albuquerque-nm", city: "Albuquerque", state: "New Mexico", stateAbbr: "NM", metro: "Albuquerque Metro", description: "Delivery services across Albuquerque and the greater New Mexico region.", stats: [{ value: "Next Day", label: "Available" }, { value: "98.8%", label: "On-Time Rate" }, { value: "300K+", label: "Annual Deliveries" }], services: ["Last-Mile Delivery", "Expedited Shipping"] },
  { slug: "tucson-az", city: "Tucson", state: "Arizona", stateAbbr: "AZ", metro: "Tucson Metro", description: "Delivery solutions across Tucson and southern Arizona.", stats: [{ value: "Next Day", label: "Available" }, { value: "99.0%", label: "On-Time Rate" }, { value: "350K+", label: "Annual Deliveries" }], services: ["Last-Mile Delivery", "Expedited Shipping"] },
  { slug: "fresno-ca", city: "Fresno", state: "California", stateAbbr: "CA", metro: "Central Valley", description: "Delivery coverage across Fresno and the greater San Joaquin Valley.", stats: [{ value: "Next Day", label: "Available" }, { value: "99.0%", label: "On-Time Rate" }, { value: "380K+", label: "Annual Deliveries" }], services: ["Last-Mile Delivery", "Expedited Shipping"] },
  { slug: "sacramento-ca", city: "Sacramento", state: "California", stateAbbr: "CA", metro: "Sacramento Metro", description: "Premium delivery services across Sacramento and California's capital region.", stats: [{ value: "Next Day", label: "Available" }, { value: "99.1%", label: "On-Time Rate" }, { value: "550K+", label: "Annual Deliveries" }], services: ["Last-Mile Delivery"] },
  { slug: "mesa-az", city: "Mesa", state: "Arizona", stateAbbr: "AZ", metro: "Phoenix Metro", description: "Serving Mesa and the East Valley as part of our comprehensive Phoenix metropolitan coverage.", stats: [{ value: "Next Day", label: "Available" }, { value: "99.0%", label: "On-Time Rate" }, { value: "400K+", label: "Annual Deliveries" }], services: ["Last-Mile Delivery"] },
  { slug: "omaha-ne", city: "Omaha", state: "Nebraska", stateAbbr: "NE", metro: "Omaha Metro", description: "Delivery services across Omaha and the greater Nebraska region, leveraging the city's central logistics position.", stats: [{ value: "Next Day", label: "Available" }, { value: "99.2%", label: "On-Time Rate" }, { value: "400K+", label: "Annual Deliveries" }], services: ["Last-Mile Delivery", "Expedited Shipping"] },
  { slug: "atlanta-ga", city: "Atlanta", state: "Georgia", stateAbbr: "GA", metro: "Atlanta Metro", description: "Premium delivery solutions across Atlanta and the greater Southeast, leveraging Atlanta's position as the logistics gateway to the Southeast.", stats: [{ value: "Next Day", label: "Available" }, { value: "99.4%", label: "On-Time Rate" }, { value: "1.2M+", label: "Annual Deliveries" }], services: ["Last-Mile Delivery"] },
  { slug: "miami-fl", city: "Miami", state: "Florida", stateAbbr: "FL", metro: "Miami Metro", description: "Comprehensive delivery services across Miami-Dade, Broward, and Palm Beach counties.", stats: [{ value: "Next Day", label: "Available" }, { value: "99.2%", label: "On-Time Rate" }, { value: "1.1M+", label: "Annual Deliveries" }], services: ["Last-Mile Delivery"] },
  { slug: "minneapolis-mn", city: "Minneapolis", state: "Minnesota", stateAbbr: "MN", metro: "Twin Cities Metro", description: "Year-round delivery solutions across the Minneapolis-Saint Paul metropolitan area.", stats: [{ value: "Next Day", label: "Available" }, { value: "99.3%", label: "On-Time Rate" }, { value: "750K+", label: "Annual Deliveries" }], services: ["Last-Mile Delivery"] },
  { slug: "cleveland-oh", city: "Cleveland", state: "Ohio", stateAbbr: "OH", metro: "Cleveland Metro", description: "Delivery services across Cleveland and Northeast Ohio.", stats: [{ value: "Next Day", label: "Available" }, { value: "99.1%", label: "On-Time Rate" }, { value: "550K+", label: "Annual Deliveries" }], services: ["Last-Mile Delivery"] },
  { slug: "tampa-fl", city: "Tampa", state: "Florida", stateAbbr: "FL", metro: "Tampa Bay Area", description: "Delivery solutions across Tampa Bay, including Hillsborough, Pinellas, and Pasco counties.", stats: [{ value: "Next Day", label: "Available" }, { value: "99.2%", label: "On-Time Rate" }, { value: "700K+", label: "Annual Deliveries" }], services: ["Last-Mile Delivery"] },
  { slug: "pittsburgh-pa", city: "Pittsburgh", state: "Pennsylvania", stateAbbr: "PA", metro: "Pittsburgh Metro", description: "Reliable delivery services across Pittsburgh and Western Pennsylvania.", stats: [{ value: "Next Day", label: "Available" }, { value: "99.1%", label: "On-Time Rate" }, { value: "500K+", label: "Annual Deliveries" }], services: ["Last-Mile Delivery"] },
  { slug: "raleigh-nc", city: "Raleigh", state: "North Carolina", stateAbbr: "NC", metro: "Research Triangle", description: "Delivery solutions across Raleigh and the Research Triangle, one of the fastest-growing markets in the Southeast.", stats: [{ value: "Next Day", label: "Available" }, { value: "99.3%", label: "On-Time Rate" }, { value: "550K+", label: "Annual Deliveries" }], services: ["Last-Mile Delivery"] },
  { slug: "cincinnati-oh", city: "Cincinnati", state: "Ohio", stateAbbr: "OH", metro: "Cincinnati Metro", description: "Strategic Cincinnati operations serving the tri-state area of Ohio, Kentucky, and Indiana.", stats: [{ value: "Next Day", label: "Available" }, { value: "99.3%", label: "On-Time Rate" }, { value: "600K+", label: "Annual Deliveries" }], services: ["Last-Mile Delivery"] },
  { slug: "kansas-city-mo", city: "Kansas City", state: "Missouri", stateAbbr: "MO", metro: "Kansas City Metro", description: "Comprehensive delivery services across Kansas City and the greater metro area spanning Missouri and Kansas.", stats: [{ value: "Next Day", label: "Available" }, { value: "99.2%", label: "On-Time Rate" }, { value: "600K+", label: "Annual Deliveries" }], services: ["Last-Mile Delivery"] },
  { slug: "st-louis-mo", city: "St. Louis", state: "Missouri", stateAbbr: "MO", metro: "St. Louis Metro", description: "Delivery solutions across St. Louis and the greater bi-state metropolitan area.", stats: [{ value: "Next Day", label: "Available" }, { value: "99.1%", label: "On-Time Rate" }, { value: "600K+", label: "Annual Deliveries" }], services: ["Last-Mile Delivery"] },
  { slug: "salt-lake-city-ut", city: "Salt Lake City", state: "Utah", stateAbbr: "UT", metro: "Wasatch Front", description: "Premium delivery services across Salt Lake City and the greater Wasatch Front region.", stats: [{ value: "Next Day", label: "Available" }, { value: "99.2%", label: "On-Time Rate" }, { value: "550K+", label: "Annual Deliveries" }], services: ["Last-Mile Delivery"] },
]

export function getLocation(slug: string): Location | undefined {
  return locations.find(l => l.slug === slug)
}
